### ISSUE TITLE
Persistent Storage

### ISSUE THREAD

**Issue by braingu-matt** [ndom91/react-timezone-select#9] opened 2020-10-12 15:14 UTC
If the values are stored in a database, then the component will need a way to set the value without the entire JSON object.

The object will change dynamically through time and not select the previously selected value that was in storage.

Recommend option set set to just be value "America/Juneau" instead. Probably would need to do a typeof check to set the value as string if it is a string, or set the value to object.value if it is an object.

**Comment by ndom91** [comment] 2020-10-12 18:17
I'm sorry I'm not sure what the problem is exactly? The values are not stored in a database, they're generated on first render in that memoized function, based on the somewhat large object at the top of the `src/index.js` file and the DST/non-DST values from `spacetime`.

**Comment by braingu-matt** [comment] 2020-10-12 18:33
Correct, but if the values are stored in a database and then set on render, the issue would arise from a mismatch.

So right now If I want the component to select America/Juneau then I need to pass the following to the value property:
```
 {
   value: 'America/Juneau'
   label: '(GMT-8:00) Alaska (AHDT)'
   altName: 'Alaskan Daylight Time'
   abbrev: 'AHDT'
 }
```

If the user selects this value and I save that JSON in the database everything works until it is no longer Daylight Savings Time. Then, when the user goes back to the field the database has the above JSON recorded but the component will not find a match because it is AHST/Alaskan Standard Time/etc.

**Comment by ndom91** [comment] 2020-10-13 11:26
Ah okay I gotcha, so you're saving the values out of this component back into a database somewhere. That's not really the intended use, but lets see if we can make it work.

Because the first part of the label '**(GMT-8:00)** Alaska (AHDT)' is generated on first render by spacetime, it is daylight savings time conscious. However, if you save these values out somewhere then you skip the spacetime generation and lose the daylight savings time adjustments that spacetime provides.

**Comment by ndom91** [comment] 2020-10-24 13:03
If there are no further questions or anything left open, @braingu-matt, then I'll close this issue this weekend.

**Closed** 2020-10-27 11:58 UTC
